version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - OTEL_SERVICE_NAME=service-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin

  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - service-b
    environment:
      - SERVICE_B_URL=http://service-b:8081/weather
      - OTEL_SERVICE_NAME=service-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_TRACES_EXPORTER=zipkin